//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sys.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Operate
    {
        public int Id { get; set; }
        public Nullable<int> MenuId { get; set; }
        public Nullable<int> ApiId { get; set; }
        public int Type { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string Icon { get; set; }
        public Nullable<int> Sort { get; set; }
        public string Remark { get; set; }
        public bool IsPublic { get; set; }
        public bool IsEnable { get; set; }
        public int CreatedBy { get; set; }
        public string CreatedByName { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public string UpdatedByName { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    
        public virtual Api Api { get; set; }
        public virtual Menu Menu { get; set; }
    }
}
