//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sys.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Privilege
    {
        public int Id { get; set; }
        public string Master { get; set; }
        public int MasterValue { get; set; }
        public string Access { get; set; }
        public int AccessValue { get; set; }
        public int Operation { get; set; }
    }
}
